### ISSUE TITLE
关于 开启账号密码登录验证, '-a user:pass'的格式参考，请问如何添加

### ISSUE THREAD

**Issue by michealhansun** [Jrohy/webssh#14]
docker run -d -a user:pass --net=host --log-driver json-file --log-opt max-file=1 --log-opt max-size=100m --restart always --name webssh -e TZ=Asia/Shanghai -e savePass=true jrohy/webssh

使用上面的命令无法运行，请问下开启登录验证具体是怎样添加命令，小白不太懂，谢谢指导

**Comment by Jrohy** [comment]
要将-a user:pass参数加到docker run命令的最后面

**Comment by michealhansun** [comment]
> 

谢谢指导，成功开启了
