### ISSUE TITLE
Request for two supports for IPv6

### ISSUE THREAD

**Issue by if1y** [Jrohy/webssh#2]
1. Whenever I tried **to connect with an IPv6 host, the websocket connection closed**. Hope this can be supported~

2. It seems **unable to run in IPv6-only server**, even I have already added 6to4 nameservers to make the server able to handle IPv4 communications.

**Comment by Jrohy** [comment]
no ipv6-only server to test 😢

**Comment by if1y** [comment]
> no ipv6-only server to test 😢

I can provide if you need. Or tell you a way I know to apply for ipv6-only free server.

**Comment by Jrohy** [comment]
tell me how to get free ipv6-only free server

**Comment by if1y** [comment]
> tell me how to get ipv6-only free server

https://www.daniao.org/8436.html

**Comment by Jrohy** [comment]
1.8 version support ipv6 server, thank u for your support

**Comment by if1y** [comment]
Just tried on server has both IPv4 & IPv6 addresses.
**Seems still unable to connect with an IPv6 host~**
<img width="482" src="https://user-images.githubusercontent.com/32222791/100989828-340ea280-358c-11eb-8c3f-9a81bb51cab8.png">

**Comment by Jrohy** [comment]
ipv6 only-server is ok, i test continue..

**Comment by if1y** [comment]
let me try later on ipv6-oly server

**Comment by Jrohy** [comment]
if u run with docker , please replace '-p 5032:5032' to '--net=host', use -p can't use in ipv6, use --net=host is ok

**Comment by Jrohy** [comment]
i fixed the readme docker run:
`docker run -d --net=host --log-driver json-file --log-opt max-file=1 --log-opt max-size=100m --restart always --name webssh -e TZ=Asia/Shanghai jrohy/webssh`

**Comment by if1y** [comment]
> if u run with docker , please replace '-p 5032:5032' to '--net=host', use -p can't use in ipv6, use --net=host is ok

seems unable to use other ports but 5032 in this way?

**Comment by Jrohy** [comment]
`docker run -d --net=host --log-driver json-file --log-opt max-file=1 --log-opt max-size=100m --restart always --name webssh -e TZ=Asia/Shanghai jrohy/webssh -p 5033`,  add `-p xxx` to docker run to change port

**Comment by if1y** [comment]
what's more:
**any way to connect to ipv4 host?**
now i'm using ipv6-only server **with nat64**

**Comment by Jrohy** [comment]
if `ssh` command can't connet ipv4 in ipv6-only server, webssh also can't connect

**Comment by if1y** [comment]
Solved with a vps (IPv4 + IPv6).
Now I can connect to both type of hosts~

---

**Thank you for effort and explaination!**
