### ISSUE TITLE
Two suggestions for improving experience

### ISSUE THREAD

**Issue by if1y** [Jrohy/webssh#3]
**1. Remembering password.** Once it's stored locally, no worry is needed~

**2. Deleting history.** Now I can achieve this by deleting local storage in F12 DevTools, but adding this function could make it easier.

**Comment by Jrohy** [comment]
1.10, support two suggestions, update it

**Comment by Jrohy** [comment]
docker run add `-e savePass=true` to save password

**Comment by if1y** [comment]
Great! Thanks for you effort!
