### ISSUE TITLE
应用可以不发布到根目录下吗？例如可以提供个设置应用名的方式，方便通过nginx来做反向代理

### ISSUE THREAD

**Issue by canwen** [Jrohy/webssh#4]
如题目所说

**Comment by Jrohy** [comment]
参考下这里配置  https://github.com/Jrohy/trojan/wiki/nginx%E9%85%8D%E7%BD%AE， 配置都差不多的

**Comment by dachun639** [comment]
大佬们使用nginx来实现了方向代码吗
