### ISSUE TITLE
中文会出现乱码

### ISSUE THREAD

**Issue by cnloveboy** [Jrohy/webssh#5]
1.目前，网页登陆使用未发现功能上的异常；
2.页面未对传输字符串编码字符集做处理，默认是utf8，对于gbk等本地显示中文为乱码，请增加字符集切换或者登录时，可以指定字符集；
希望能得到回复：xuyuanjun@foxmail.com

**Comment by Jrohy** [comment]
不支持, 默认linux也是不支持gbk的乱码的

**Comment by Jrohy** [comment]
websocket传输默认也只支持utf8, 不想加base64来添加性能负担
