### ISSUE TITLE
建议新增密钥证书方式登录

### ISSUE THREAD

**Issue by he-jialin** [Jrohy/webssh#7]
目前只能纯密码登录，建议新增通过密钥文件登录。
wiki里面可以贴支付宝或者微信收款码 可以打赏维持更新

**Comment by Jrohy** [comment]
收款码就没必要了有风险，可行性会先看下，只要有新点子会持续更新的

**Comment by Jrohy** [comment]
1.21版本已添加密钥登录，更新下

**Comment by Jrohy** [comment]
1.21版本已增加密钥登录，更新下
